const Books = [
    { 
      "id": "001",
      "author": "Chinua Achebe",
      "price":6000,
      "country": "Nigeria",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/thumb/6/65/ThingsFallApart.jpg/220px-ThingsFallApart.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
      "pages": 209,
      "title": "Things Fall Apart",
      "year": 1958
    },
    {
      "id": "002",
      "author": "Hans Christian Andersen",
      "price":8000,
      "country": "Denmark",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Hans_Christian_Andersen_%281834_painting%29.jpg/220px-Hans_Christian_Andersen_%281834_painting%29.jpg",
      "language": "Danish",
      "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
      "pages": 784,
      "title": "Fairy tales",
      "year": 1836
    },
    {
      "id": "003",
      "author": "Dante Alighieri",
      "price":2100,
      "country": "Italy",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Dante_Domenico_di_Michelino_Duomo_Florence.jpg/323px-Dante_Domenico_di_Michelino_Duomo_Florence.jpg",
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
      "pages": 928,
      "title": "The Divine Comedy",
      "year": 1315
    },
    {
      "id": "004",
      "author": "Unknown",
      "price":4700,
      "country": "Sumer and Akkadian Empire",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/British_Museum_Flood_Tablet.jpg/220px-British_Museum_Flood_Tablet.jpg",
      "language": "Akkadian",
      "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
      "pages": 160,
      "title": "The Epic Of Gilgamesh",
      "year": -1700
    },
    {
      "id": "005",
      "author": "Unknown",
      "price":5420,
      "country": "Achaemenid Empire",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Aleppo_Codex_Joshua_1_1.jpg/220px-Aleppo_Codex_Joshua_1_1.jpg",
      "language": "Hebrew",
      "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
      "pages": 176,
      "title": "The Book Of Job",
      "year": -600
    },
    {
      "id": "006",
      "author": "Unknown",
      "price":3400,
      "country": "India/Iran/Iraq/Egypt/Tajikistan",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Cassim.jpg/220px-Cassim.jpg",
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
      "pages": 288,
      "title": "One Thousand and One Nights",
      "year": 1200
    },
    {
      "id": "007",
      "author": "Unknown",
      "price":1200,
      "country": "Iceland",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Njal_saga_-_Skarphedinn.jpg/220px-Njal_saga_-_Skarphedinn.jpg",
      "language": "Old Norse",
      "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
      "pages": 384,
      "title": "Nj\u00e1l's Saga",
      "year": 1350
    },
    {
      "id": "008",
      "author": "Jane Austen",
      "price":4000,
      "country": "United Kingdom",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/PrideAndPrejudiceTitlePage.jpg/220px-PrideAndPrejudiceTitlePage.jpg",
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
      "pages": 226,
      "title": "Pride and Prejudice",
      "year": 1813
    },
    {
      "id": "009",
      "author": "Honor\u00e9 de Balzac",
      "price":2000,
      "country": "France",
      "imageLink": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Le_P%C3%A8re_Goriot%2C_1er_Volume%2C_1835.png/220px-Le_P%C3%A8re_Goriot%2C_1er_Volume%2C_1835.png",
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
      "pages": 443,
      "title": "Le P\u00e8re Goriot",
      "year": 1835
    },
    {
      "id": "010",
      "author": "Samuel Beckett",
      "price":1000,
      "country": "Republic of Ireland",
      "imageLink": "https://upload.wikimedia.org/wikipedia/en/9/90/Beckett_Molloy.jpg",
      "language": "French, English",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
      "pages": 256,
      "title": "Molloy",
      "year": 1952
    },
    {
      "id": "011",
      "author": "Montaser",
      "price":3020,
      "country": "Egypt",
      "imageLink": "http://t2.gstatic.com/images?q=tbn:ANd9GcRTgSdSDt57Tr3XuFy9PmiQg2jaoCJ62nR1xX1VxYNzKD6aT3eC",
      "language": "Arabic",
      "link": "noor-book.com/en/z3xrug\n",
      "pages": 450,
      "title": "Al-ahly Sports Club",
      "year": 1907
    },
    {
      "id": "012",
      "author": "Naguib Mahfouz",
      "price":5180,
      "country": "Egypt",
      "imageLink": "https://res.cloudinary.com/dyfwbiuro/image/upload/v1681564440/yf9sutz8bz0cfqtc0h5m.jpg",
      "language": "Arabic",
      "link": "https://bookssaw.netlify.app/bookpage/6437429d8d5c2b5540581b7e\n",
      "pages": 450,
      "title": "Khan El-Khalily",
      "year": 1907
    }
];